### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by evitada** [sehaas/yfmos#2]
Hi,

maybe i am missing something but i always getting same error -

  File "yfmos.py", line 324
    raise NameError('Profile '%s' not found' % profile)
                                           ^
SyntaxError: invalid syntax

what i am doing wrong ?

**Comment by sehaas** [comment]
I messed up the quoting during refactoring. It should be fine now.

**Comment by evitada** [comment]
thank you very much, it is working know, 
i successfully confirm the rf bridge as new remote with a movement of the shades. 
but i dont understand what to do after in order to control the shades ?

**Comment by sehaas** [comment]
You can use `UP`, `DOWN` or `MY` as commands to control them.
Generate the B0 string:
```
python yfmos.py gen --profile kitchen --repeat 8 --command UP
```
or generate the B0 string and send it directly to the RF bridge:
```
python yfmos.py run --host http://<RFBridgeIP> --profile kitchen --repeat 8 --command UP
```
With the repeat parameter you can define if the command acts like a short or long press on the button.

**Comment by evitada** [comment]
Thank you very much, its working !
now, just for understanding, the B0 string is only for one time use current ?
so need to generate new B0 string for every use ?
once again, thank you for all of your help. 

update-
it works only when generating B0 string and using console to send it, 
send it directly from your script to the RF bridge doesn't working.
