### ISSUE TITLE
Multiple questions: theory, frequency, http send

### ISSUE THREAD

**Issue by mgoeller** [sehaas/yfmos#4]
Hi, thank you for this git.

I managed to get my Somfy blinds working with the Sonoff Bridge flashed with Tasmota and the Portisch firmware. However I have a few questions:

1. I guess sending the generated PROG B0 code while the according shades are in programming mode, pairs the Sonoff Bridge as a new remote, correct? 

2. Why do we have to repeat the small UP and DOWN commands? Is that because the RTS protocol is still not completely deciphered? The behaviour of how many repetitions doesn't seem linear. E.g. 8reps only closes ~2cm, 50reps ~20cm and 100reps 100cm. Is that normal behaviour?

3. I read in another git, that the actual frequency of the Somfy is 433.42 MHz and they replaced the oscillator. Can one also replace the one on the Sonoff Bridge. Did anyone find a compatible oscillator in this long instead of round format?

4. I receive the following error using the host argument. I'm not using mqtt, so I would be glad for an alternative to the direct console RfRaw sending method. Any help?
`Error calling "http://192.168.0.96": 404`

Thank you!

**Comment by Denao2** [comment]
mgoeller,
I too am using this for my blinds. I am not the author of this work, but according to my understanding, my response to your questions:
1) Doesnt pair the bridge as such, but rather to the device hex you set as part of the profile (or the default if you dont specify one). The distinction is important as you can many virtual remotes coming from the same RF Bridge (I have one for each of my three blinds and one paired to all of them)
2) I dont get this behavour. Issuing the command causes my blinds to transit to their preset positions. 
3) I had read this too but it doesn't appear to be an issue for me.
4) I too had this problem and had to tweek the code. I have sent a pull request #3 to fix this but I need to tweak it before it can be merged. (See pull request thread)
Regards,
Dean

**Comment by sehaas** [comment]
Hi mgoeller,
as Denao2 already wrote:
1.) You get the bucket timings from the B1 string. With this information you register a new virtual device (unique HEX id) on your receiver. Afterwards you can use this HEX on any RF Bridge.

2.) AFAIK the number of frames does not correlate directly with the distance. According to this [pushstack's blogpost](https://pushstack.wordpress.com/somfy-rts-protocol/), a single button press sends a single frame. Holding the button will repeat the same frame (same command and same rolling code) multiple times. The receiver/motor can interpret this as:
* single frame (single button click)-> all the way to the end position
* multiple frames (holding the button) -> drive the motor as long as the button is pressed
* or vice versa.

It's somewhere in the Somfy documentation how to swap this behaviour.
I'm pretty sure this code isn't a 100% correct implementation of the protocol, but at least my blindes respond to most commands ;)

3.) The receiver seams to be tolerant enough to accept the slightly different frequency. Maybe you get a better coverage or you can have more walls in between if you're using the exact frequency.
